# Generated by Django 6.0.5 on 2026-07-10 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_module_author_alter_module_description_and_more'),
        ('resident_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentinfofields',
            name='registered_region',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='户籍地址省市区'),
        ),
        migrations.AlterField(
            model_name='residentinfofields',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_relation_residents', to='core.taxonomyitem', verbose_name='与户主关系'),
        ),
    ]
