# Generated by Django 6.0.3 on 2026-03-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentinfofields',
            name='id_card',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号'),
        ),
    ]
