# Generated by Django 6.0.5 on 2026-07-16 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident_info', '0002_alter_residentinfofields_registered_region_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residentinfofields',
            options={'ordering': ['name'], 'verbose_name': '居民', 'verbose_name_plural': '居民'},
        ),
    ]
