# Generated by Django 6.0.3 on 2026-03-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident_info', '0002_alter_residentinfofields_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentinfofields',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系电话'),
        ),
    ]
